#!/data/data/com.termux/files/usr/bin/bash

clear
kill_color=$'\e[0m'
command -v youtube-dl &>/dev/null || printf "\e[031m Please install Youtube-dl manualy or run the the install.sh script again.\n$kill_color"

#uncomment me if you wish :)
#[[ -f ~/bin ]] || printf "\e[031m Please Run the the install.sh script.\n$kill_color"


echo -e "\033[92m      ##  #######  ##    ## ######## ########  "
echo -e '\033[91m      ## ##     ## ##   ##  ##       ##     ## '
echo -e '\033[92m      ## ##     ## ##  ##   ##       ##     ## '
echo -e '\033[91m      ## ##     ## #####    ######   ########  '
echo -e '\033[92m##    ## ##     ## ##  ##   ##       ##   ##   '
echo -e '\033[91m##    ## ##     ## ##   ##  ##       ##    ##  '
echo -e '\033[92m ######   #######  ##    ## ######## ##     ## '
echo -e '\n\033[92m°°°°°°°\033[91m°°°°°°°°°\033[92m°°°°°°°°°°\033[91m°°°°°°°\033[92m°°°°°°°°°°\033[91m°°°°\033[92m\n\033[91m° \033[91m[\033[92m×\033[91m]\033[92m 𝘼𝙐𝙏𝙃𝙊𝙍  \033[93m  : \033[91m 𝙈𝙍 𝙅𝙊𝙆𝙀𝙍                   \033[92m°\n\033[91m° \033[91m[\033[92m×\033[91m]\033[92m 𝙂𝙄𝙏𝙃𝙐𝘽   \033[93m : \033[91m 𝙈𝙍-𝙅𝙊𝙆𝙀𝙍-69                \033[92m°\n\033[91m°\033[91m [\033[92m×\033[91m]\033[92m 𝙒𝙃𝘼𝙏𝙎𝘼𝙋𝙋  \033[93m: \033[91m 01750376469                \033[92m°\n\033[92m°°°°°°°\033[91m°°°°°°°°°\033[92m°°°°°°°°°°\033[91m°°°°°°°\033[92m°°°°°°°°°°\033[91m°°°°'
echo -e '\033[91m[\p33[92m1\033[91m] \033[92m MP3 DOWNLOAD MUSIC'
echo -e '\033[91m[\033[92m2\033[91m] \033[92m 360P DOWNLOAD VIDEO'
echo -e '\033[91m[\033[92m3\033[91m] \033[92m 480P DOWNLOAD VIDEO'
echo -e '\033[91m[\033[92m4\033[91m] \033[92m 720P DOWNLOAD VIDEO'
echo -e '\033[91m[\033[92m5\033[91m] \033[92m 1080P DOWNLOAD VIDEO'
echo -e '\033[91m[\033[92m6\033[91m] \033[92m 2160P DOWNLOAD VIDEO'
echo -e '\033[91m[\033[92m7\033[91m] \033[92m EXIT TOOLS'
command='-no-mtime -o /data/data/com.termux/files/home/storage/shared/Youtube/%(title)s.%(ext)s -f'

#Edit From Oak Atsume 
print'\033[91m[\033[92m×\033[91m] CHOOSE \033[93m: '
read option

if [[ -z $option ]];
then
	clear
	printf "\e[031m Please choose a option!\n$kill_color"
else
case $option in #Make Case list
	1)
	echo "$command 140" > ~/.config/youtube-dl/config #option 1
	youtube-dl $1
	;;
	2)
	echo "$command \"best[height<=360]\"" > ~/.config/youtube-dl/config #option 2
	youtube-dl $1
	;;
	3)
	echo "$command \"best[height<=480]\"" > ~/.config/youtube-dl/config #option 3
	youtube-dl $1
	;;
	4)
	echo "$command \"best[height<=720]\"" > ~/.config/youtube-dl/config #option 4
	youtube-dl $1
	;;
	5)
	echo "$command \"best[height<=1080]\"" > ~/.config/youtube-dl/config #option 5
	youtube-dl $1
	;;
	6)
	echo "$command \"best[height<=2160]\"" > ~/.config/youtube-dl/config
    	youtube-dl $1
	;;
	7)
	break
	;;
esac 
fi
